### ISSUE TITLE
Upload to SFtp

### ISSUE THREAD

**Issue by PRijnbeek** [ohdsi-studies/Covid19CharacterizationCharybdis#38]
1. The package is not generating AllResults_<database>.zip but Results_<database> so it will generate an error saying you did not run the package when uploading to sSTP

2. If i change the name it is uploading to a cohortEvaluation folder and it should go to a study package  named folder with a subfolder "CohortDiagnostics" instead. Otherwise you cannot know the study this is coming from.

3. It is not clear from the instructions how to upload all the diagnostics. I now did it manually by add all the folders with only the results.zips in one AllResults_Diagnostics_IPCI zip file. We need to make this easier for databases. Add uploadDiagnostics that saves in a StudyPackage folder or even better combine both if diagnostics did run.

**Comment by anthonysena** [comment]
Glad we are at the point where we're uploading results :+1:

To that end, let me address some points here:

> The package is not generating AllResults_.zip but Results_ so it will generate an error saying you did not run the package when uploading to sSTP

Oversight on my part - I will update this.

> If i change the name it is uploading to a cohortEvaluation folder and it should go to a study package named folder with a subfolder "CohortDiagnostics" instead. Otherwise you cannot know the study this is coming from.

Agreed - I'd propose we have a main folder "/CHARYBDIS" off of the root. Under there, we should have subfolders: "CohortDiagnostics" and "StudyResults" to hold the respective outputs of the package.

> It is not clear from the instructions how to upload all the diagnostics. I now did it manually by add all the folders with only the results.zips in one AllResults_Diagnostics_IPCI zip file. We need to make this easier for databases. Add uploadDiagnostics that saves in a StudyPackage folder or even better combine both if diagnostics did run.

Since running the diagnostics and study are different functions, I'd propse we have different calls to upload results where we can specify the folders mentioned above. I'll also add to the diagnostics function a way to ZIP up all of the diagnostics into a single file for upload.
