### ISSUE TITLE
User friendly cohort table

### ISSUE THREAD

**Issue by kmkostka** [ohdsi-studies/Covid19CharacterizationCharybdis#4]
Similar to what Marc did for LEGEND, we should make a page in the GitHub repo that makes it easy to look through the Cohorts we built (so people can reuse them for other studies).

**Comment by anthonysena** [comment]
I'd like to see if we can make this a markdown file that we include in the `/inst/settings/shiny' folder somewhere so that we can share it between the repository and the Shiny results viewer. We can link to it from the main README page for those interested in getting to it from the repo and thinking there may be a way to easily display in Shiny.

**Comment by kmkostka** [comment]
Here's what I was thinking: https://github.com/OHDSI/Legend/blob/master/Documents/CohortDefinitionTable.csv

This but because we have so many different ones, we would need to collapse it to one "Phenotype Library" table. I'll work on this.

**Comment by kmkostka** [comment]
Created initial pass: https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/blob/master/documents/CharybdisPhenotypeLibrary.csv

Need to find a couple of missing links and will revisit user friendly utility.

**Comment by anthonysena** [comment]
This was done both using the .csv mentioned above along with links to the cohort definitions on atlas.ohdsi.org.
